### ISSUE TITLE
Carabiner forces BPM when joining partner

### ISSUE THREAD

**Issue by mungewell** [Deep-Symmetry/carabiner#12]
When starting Carabiner most of the time it jumps itself to whatever bpm the other device is working at, but sometimes it forces the partner to jump to 120bpm. I don't know whether this is part of the protocol. or a bug with my partner application (Desktop MPC).

Is there some way to debug the link, or an explanation on why this might happen

**Comment by brunchboy** [comment]
I am afraid I don’t really understand the question, or what you mean by “partner application”. I have never heard of Desktop MPC, but you might want to ask them?

Carabiner doesn’t change the Link session tempo unless it receives an instruction to do so over its control socket.

The only way I know of “debugging” a Link session is using Ableton’s LinkHUT monitoring/testing tool. That is part of the Link source code. The details of the protocol are also documented there. (There are hyperlinks to the Ableton Link repository near the top of the Carabiner project page.)

**Comment by brunchboy** [comment]
Also, the source code for Carabiner is very short; I would encourage you to take a look at that after you look at the Link documentation. It is an extraordinarily simple bridge program.

**Comment by mungewell** [comment]
> I have never heard of Desktop MPC, but you might want to ask them?

Already did :-)
https://getsatisfaction.com/akai_professional/topics/mpc-2-6-losing-connection-to-ableton-link

Seems that the new version (v2.6) of MPC maybe having issues with Albeton Link, and I found/was hoping Carabiner would be a useful debug tool.

As I said most of the time it works. I guess I need to do some reading to understand at what point in the protocol negotiation that an app/device believes it is the definitive BPM reference for new partners.

**Comment by brunchboy** [comment]
Ah, if you are not actually trying to use software that depends on Carabiner to bridge to a Link session, I would suggest skipping it and building and using LinkHut directly for that purpose. The source code and instructions are [here](https://github.com/Ableton/link).

**Comment by mungewell** [comment]
Just debugging/playing for now.... the fact that Carabiner is a small/pre-built binary made it attractive.
Longer term I might used the referenced Python connector to do 'cool stuff'. Thanks.

**Comment by brunchboy** [comment]
You’re welcome. I’m going to close this issue since there’s nothing actionable by the Carabiner project.
