### ISSUE TITLE
libatomic not linked

### ISSUE THREAD

**Issue by Xartrick** [Deep-Symmetry/carabiner#15]
## The Bug
When building using `CMake`, ` libatomic` is not linked.

```
xartrick@sylvanas:~/dev/carabiner/build$ cmake --build .
[..]
[ 71%] Linking CXX executable bin/Carabiner
/usr/bin/ld: CMakeFiles/Carabiner.dir/carabiner.cpp.o: in function `std::__atomic_base<unsigned long>::is_lock_free() const':
carabiner.cpp:(.text._ZNKSt13__atomic_baseImE12is_lock_freeEv[_ZNKSt13__atomic_baseImE12is_lock_freeEv]+0x19): undefined reference to `__atomic_is_lock_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/Carabiner.dir/build.make:100: bin/Carabiner] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/Carabiner.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

## How to reproduce
1. Clone the repository ;
2. Follow `Building` on `README.md` ;
3. See error.

## Workaround
Add `atomic` to `target_link_libraries` in `CMakeLists.txt`.

## Environment
* OS: Ubuntu 19.10
* Project version: `master`

**Comment by brunchboy** [comment]
I’ve not seen this problem, but I don’t have ubuntu on any hardware that could talk to a Link network. Would you be able to submit a fix as a pull request that does not cause any problems on debian/raspbian, macOS or Windows?

**Comment by brunchboy** [comment]
And thank you for this report! 😄

**Comment by Xartrick** [comment]
I don't have any macOS to test it, but I can test on other platforms. I'll test it on other OS and create a PR after that.

This seems to be related : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358

**Comment by brunchboy** [comment]
Ok, I can do the macOS testing for you. I can’t really follow the discussion in that bug link because I haven’t been part of the c/c++ community for decades now, alas.

Thanks!

**Comment by brunchboy** [comment]
If there is no further activity on this I am going to close the issue soon. If you found a way to fix the issue, please submit a PR.
