### ISSUE TITLE
Carabiner MacOs Installation

### ISSUE THREAD

**Issue by plusmoremusic** [Deep-Symmetry/carabiner#16]
Hello,

When i try to install the .dmg on my Macbook it shows me the errormessage: "filesystem not found".
Can someone help me out?
I installed the Beat Link Trigger.jar via Terminal and connected my CDJ's, but i cant run Carabiner.
Regards
Henrik

**Comment by brunchboy** [comment]
I can’t reproduce this with either the latest release or the preview/snapshot of the forthcoming release, on macOS Mojave (10.14.6) or Catalina (10.15.4). I would suspect overzealous anti-virus software or some other system problem, and suggest you ask Apple for support?

**Comment by brunchboy** [comment]
More fundamentally, it is no longer necessary to install Carabiner separately to use it with Beat Link Trigger. Since version 0.6.1 of Beat Link Trigger, a copy of Carabiner is embedded inside Beat Link Trigger, and automatically extracted and run when you need it.

**Comment by brunchboy** [comment]
Also, why are you installing Beat Link Trigger via jar? Are you having the same problem with disk images for that? There seems to be something wrong with your system that definitely needs attention.

**Comment by brunchboy** [comment]
Finally, very few people, probably only me, look at the issues, especially in the Carabiner project. For general questions, and perhaps some hope of running into a user who has solved a similar problem, the best venue is the Beat Link Trigger [Gitter channel](https://gitter.im/brunchboy/beat-link-trigger). Thanks for experimenting with these things, and best of luck getting them working how you’d like!

**Comment by plusmoremusic** [comment]
Hello. Thanks for the help. Problem solved.
Im using MacOs 10.11 El Capitan. 
I cant install the .dmg installers of Carabiner or Beat Link Trigger.
But I have just started the older version of Carabiner via Terminal now.

**Comment by brunchboy** [comment]
Thanks for the update @plusmoremusic. You should always run the latest version of my projects, though: there have been many fixes and improvements over the years. How frustrating that the disk images that Apple creates today will not open on older operating systems. What version of Beat Link Trigger are you using? If it is recent enough you should not need to install or run Carabiner separately. If there is some reason you really need to run it on its own, outside of Beat Link Trigger, I could send you a more current build outside of a disk image, or you could perhaps build it from source yourself?

**Comment by brunchboy** [comment]
I just realized what is going on. The `hdiutil` command I am using to create the disk images is defaulting to the new APFS filesystem format, which was not supported by High Sierra (10.12) or earlier. I am going to try to see if I can still notarize the disk image successfully even if I use the older HFS+ (MacOS Extended) filesystem format, which would let people on very old operating systems still open the images.

**Comment by brunchboy** [comment]
@plusmoremusic could you try downloading the latest snapshot release? I think you should be able to open the disk image now! If so, I will adjust the Beat Link Trigger build to create HFS+ disk images as well, so you can use the DMG there as well. The Mac application provides a nicer user experience than the raw jar file does. https://github.com/Deep-Symmetry/carabiner/releases/tag/v0.1.4-SNAPSHOT

**Comment by brunchboy** [comment]
I have updated the Beat Link Trigger build workflow as well, and it is now generating HFS+ disk images. Could you try the disk image from the latest snapshot, which I am getting close to releasing? https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/v0.6.2-SNAPSHOT

**Comment by plusmoremusic** [comment]
Thanks mate!
Now both are working perfectly on my El Capitan.
Good job.

**Comment by brunchboy** [comment]
Sweet, thanks for the confirmation. I am sure you’re not the last person who will run into this, so I will do new releases this weekend so even people who stick to formally released versions will get compatible disk images.
