### ISSUE TITLE
V1.1.3 release - Windows 10 install fail

### ISSUE THREAD

**Issue by mungewell** [Deep-Symmetry/carabiner#17]
Error message "VCRUNTIME140_1.dll not found" on attempting to install on Windows 10.

![carabiner_install_fail](https://user-images.githubusercontent.com/236907/82504478-0334b780-9aeb-11ea-9732-f9c9e5aa4ab3.png)

![about_win_java](https://user-images.githubusercontent.com/236907/82504608-57d83280-9aeb-11ea-8293-f205e39af420.png)

**Comment by brunchboy** [comment]
Hi! I can’t offer Windows support, but if you can figure out how to fix this, a pull request would be most welcome.

**Comment by brunchboy** [comment]
One thing I notice is that you are trying Windows 10 Home, and I believe that it is built against Windows 10 Professional. You might want to try installing a current Visual Studio C++ development environment, and see if that installs the necessary libraries.

**Comment by brunchboy** [comment]
Failing that, you should at least be able to build it yourself from source then.

**Comment by mungewell** [comment]
Understood regarding the above comments. Will try a few things...

Also checked v0.1.4-SNAPSHOT, has same issue.

**Comment by brunchboy** [comment]
Yes, nothing has changed about the Windows build process since it was moved to continuous integration through GitHub Actions. You can find the job [here](https://github.com/Deep-Symmetry/carabiner/blob/19a5e2ce0d595db34bdabeebbedea990c67faaca/.github/workflows/build.yml#L23-L64).

**Comment by mungewell** [comment]
Yes, it was a problem with re-distributable, installed from here and Carabiner now works.
https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads

**Comment by brunchboy** [comment]
Thanks for the report! I am going to reopen this because it would be nice if the binaries built by GitHub would just work for people. If you can think of any way to change the build job to include them, please let me know, or we may need to open an issue with GitHub to update the environment for GitHub Actions. Actually, perhaps they have, and we just need to run a new build of the snapshot release?

**Comment by brunchboy** [comment]
I think this has been resolved. Please reopen it if I am wrong.
