### ISSUE TITLE
Prebuilt binary crashes on MacOS 10.13.6

### ISSUE THREAD

**Issue by tamlyn** [Deep-Symmetry/carabiner#18]
**Describe the bug**
I tried downloading `1.1.3` and `v0.1.4-SNAPSHOT` and both crash on start with the following output:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Carabiner (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding faileddyld: Symbol not found: ____chks: Symbol not found: ____chkstk_dtk_darwin
  Referenced from: /Aparwin
  Referenced from: /Applicplications/Carabiner (which was ations/Carabiner (which was builbuilt for Mac OS X 10.15)
  Expet for Mac OS X 10.15)
  Expectedcted in: /usr/lib/libSystem.B.dy in: /usr/lib/libSystem.B.dylib
lib


dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Carabiner (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

When I build from source I get a binary that works. I realise that my OS version is pretty old so perhaps you don't support it.

**Desktop (please complete the following information):**
 - OS: `macOS 10.13.6`
 - Java Version `openjdk version "13.0.2" 2020-01-14`
 - Project Version `1.1.3`

**Comment by brunchboy** [comment]
Thanks for the report! Indeed I no longer have access to systems running that OS version, and am not a C++ developer, so I don’t think there is anything I can do about this. If anyone knows how to fix it, a pull request would be appreciated.

**Comment by brunchboy** [comment]
Also, I should fix the issue report template if it’s asking people for java versions, since Carabiner doesn’t use Java! :smile:

**Comment by brunchboy** [comment]
I’ve just heard from someone else who has this problem, would you be willing to share your built version with him?

**Comment by brunchboy** [comment]
Actually, I think I may have found out how to fix this for everyone! Could you try the version that is currently building? If it works on your system, I will update Beat Link Trigger to embed this as well.

https://github.com/Deep-Symmetry/carabiner/releases/tag/v0.1.4-SNAPSHOT

**Comment by tamlyn** [comment]
That works 🎉  Thanks.

**Comment by brunchboy** [comment]
Great, thanks for confirming! I think this will be worth putting out a new release of Carabiner this evening, and then I will pull it into lib-carabiner and Beat Link Trigger.

**Comment by brunchboy** [comment]
All right, there were so many intermediate libraries to update, and I needed to switch to a new way of publishing to Clojars because of security improvements on their end, but Beat Link Trigger has been updated and is now building a new snapshot release that includes this fix. 😄 Time to close the issue.
