### ISSUE TITLE
Late/Slow response from beat_at_time() and time_at_beat()

### ISSUE THREAD

**Issue by mungewell** [Deep-Symmetry/carabiner#22]
Continuing my adventures with LinkToPy and Carabiner... I have an example program which toggles between two/multiple tempos, it tracks the differences between AbletonLink time and CPU time and schedules tempo change to happen on the downbeat of a bar.

I used the `time_at_beat()` and `beat_at_time()` calls to calculate the desired times, however I am seeing that sometimes the callbacks do not complete in a timely manner (ie > 1.0s), risking the integrity of the scheduling. If I re-call the function the callback appears to complete quickly.
https://github.com/mungewell/LinkToPy/blob/examples/example/toggle_bpm.py#L115

How quickly should these respond, what's a sensible maximum/timeout value?

My onscreen debug gives
```
Tempo change scheduled for beat: 5364.000000 @ 229185.327975 (now 229193.939212)
Tempo set to: 90.000000  (beat: 5363.983610 @ 229193.947327)

Tempo change scheduled for beat: 5380.000000 @ 229194.042372 (now 229204.595869)
Tempo set to: 110.000000  (beat: 5379.998919 @ 229204.606412)

Tempo change scheduled for beat: 5396.000000 @ 229204.689938 (now 229213.334753)
Tempo set to: 90.000000  (beat: 5395.995767 @ 229213.342822)

TimeAtBeat slow response!
Tempo change scheduled for beat: 5412.000000 @ 229214.431901 (now 229223.997288)
Tempo set to: 110.000000  (beat: 5412.012508 @ 229224.006812)

Tempo change scheduled for beat: 5428.000000 @ 229224.083124 (now 229232.715028)
Tempo set to: 90.000000  (beat: 5427.975556 @ 229232.722845)
```

I am running on Xubuntu, with Carabiner 1.1.6.

**Comment by brunchboy** [comment]
Please ask Link questions on the [Ableton Link repository](https://github.com/Ableton/link), I can’t answer them. Carabiner is a tiny wrapper around Link and does almost nothing, as you can see if you look at the [source](https://github.com/Deep-Symmetry/carabiner/blob/main/carabiner.cpp). You may be experiencing network latency issues, but I have never seen anything even coming close to that on my own network. I’m afraid I can’t help troubleshoot this, though; I’m not a C++ developer, and I did just enough work on this to get it working so I could use it in my own projects, and it seems to work reliably for me and my users.

**Comment by brunchboy** [comment]
Another thing you could try doing is capturing packets with Wireshark and seeing where the delay seems to be taking place. Does python have a performance monitoring tool that can track when methods are called and when they respond? That might help narrow things down as well. I am wondering if some I/O is configured wrong somewhere? I have never seen callbacks take perceptible time.

**Comment by mungewell** [comment]
I'll continue to dig, but I may be missing understanding of how Script -> LinkToPy -> Carabiner -> AbletonLink is actually functioning.

Rather than being 'late' I think it's likely that the callback never happens (ie request is silently dropped). _I need to check that the call to `link.beat_at_time()` doesn't throw an error._

I'll note that I also see this on Windows 10, and also when the external network is not enabled. This means nothing connected in a session. Carabiner reports
```
Starting Carabiner 1.1.6 on port tcp://127.0.0.1:17000
Link bpm: 90 Peers: 0 Connections: 1
```

I see the tempo toggling and occasionally my events waiting for callback timeout.
```
Tempo change scheduled for beat: 372.000000 @ 673.890000 (now 682.586745)
Tempo set to: 90.000000  (beat: 372.009124 @ 682.593000)

Tempo change scheduled for beat: 388.000000 @ 682.625000 (now 693.255911)
Tempo set to: 110.000000  (beat: 388.019873 @ 693.265000)

Tempo change scheduled for beat: 404.000000 @ 693.296000 (now 701.977698)
BeatAtTime slow response!
Tempo change scheduled for beat: 420.000000 @ 702.515000 (now 712.541876)
Tempo set to: 110.000000  (beat: 420.015586 @ 712.546000)

Tempo change scheduled for beat: 436.000000 @ 712.578000 (now 721.273186)
Tempo set to: 90.000000  (beat: 436.029192 @ 721.281000)

Tempo change scheduled for beat: 452.000000 @ 721.328000 (now 731.935783)
```

**Comment by brunchboy** [comment]
Yeah, that’s the kind of thing where watching the network traffic with Wireshark and maybe the system calls as well can help pinpoint where things are getting lost. Although I think I may have heard that watching local network communication on Windows is difficult or impossible?

**Comment by mungewell** [comment]
I am not seeing errors returned from the calls to `beat_at_time()`, and then went on to add Threading `lock()` as I thought it might be a problem with the multiple threads I have going... still giving an occasional fail :-(

**Comment by brunchboy** [comment]
Oh, if you have multiple threads involved, you should make sure only one thread talks to Carabiner, or they may steal or step on each others’ messages.

It may be sufficient to have a single thread handling responses from Carabiner, but it wasn’t designed with concurrency in mind, so you’ll want to study it carefully and think about that.

**Comment by brunchboy** [comment]
I guess that is a bit of an overstatement; in my own implementations I certainly use concurrency, but I definitely have a single thread processing all responses from Carabiner, and carefully use Clojure’s concurrency mechanisms (largely atoms and `swap!`) to communicate responses with other threads. That code is in https://github.com/Deep-Symmetry/beat-carabiner/blob/main/src/beat_carabiner/core.clj

**Comment by mungewell** [comment]
Thanks for all the suggestions, the code is at a working point - I'll try to track down this issue at some time in the future.
