### ISSUE TITLE
[Windows] Problem with .dll-Files

### ISSUE THREAD

**Issue by MLK97** [Deep-Symmetry/carabiner#8]
On what Visual C++ Version was this tested? I tried the software with the 2015 version and the 2017 version, but always got the error message that needed .dll-files don't exist, even though they exist.
I've been trying different .dll Files etc. but nothing seems to solve the problem

**Comment by brunchboy** [comment]
I’m sorry, I don’t remember, and am not even sure how to tell. I can’t really offer Windows support, but would welcome pull requests if you find a way to get it working reliably.

**Comment by MLK97** [comment]
Yes I will try some other alternatives that are recommended and see whether or not it is a issue with my device or some complication between your version and Visual C++ and see if I can fix it

**Comment by brunchboy** [comment]
Great, thanks, I look forward to hearing anything that you discover. I also want to be sure you saw the discussion in https://github.com/Deep-Symmetry/carabiner/issues/4 where I learned how to build it at all.

**Comment by LucaMagnino95** [comment]
I'm trying to run Carabiner_Win_64 but catch error 0xc000007b. What can I do?
![image](https://user-images.githubusercontent.com/23115431/51596874-31f04d00-1efa-11e9-95e1-bb359609f299.png)

**Comment by brunchboy** [comment]
Unfortunately, I can’t offer Windows support. If you know any Windows developers, see if they can figure it out; if they can, please ask them to make a pull request with any necessary changes.

**Comment by brunchboy** [comment]
I just uploaded a new build that was compiled in Release mode, this may solve the problem people have been having with missing DLLs. Please give it a try.
